### 2.1. Data Manipulation

- Tensors: n-dimensional arrays to store data

- Tensor class: ndarray in MXNet, Tensor in PyTorch and TensorFlow


#### 2.1.1. Getting Started

In [2]:
# pytorch
import torch
x = torch.arange(12, dtype=torch.float32)

print(x)
print(x.numel())
print(x.shape)

x = x.reshape(3, 4)
print(x)

print(torch.zeros((2,3,4)))
print(torch.ones((2,3,4)))
print(torch.randn(3,4))

print(torch.tensor([2,2]) , torch.tensor([2,2]) .shape)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[-1.1383,  0.4034,  1.7138,  0.1386],
        [-0.1619, -0.6064,  1.3564, -1.7578],
        [-0.7292, -0.2459, -0.8360, -0.5222]])
tensor([2, 2]) torch.Size([2])


#### 2.1.2. Indexing and Slicing


In [3]:
# axis = 0 -> row
print(x[-1])
print(x[1:3])

x[1, 2] = 17
print(x)

x[:2, :] = 12
print(x)

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


#### 2.1.3. Operations

In [4]:
# elementwise operations
print(torch.exp(x))
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [5]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [6]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

#### 2.1.4. Broadcasting

In [7]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, b)
a+b

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

#### 2.1.5. Saving Memory

In [8]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [9]:
Z = torch.zeros_like(Y) # not overwrite Y
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
print('id(X), id(Y):', id(X), id(Y))

id(Z): 140468942606704
id(Z): 140468942606704
id(X), id(Y): 140469197147120 140468398954832


In [10]:
before = id(X)
X += Y
id(X) == before

True

#### 2.1.6. Conversion to Other Python Objects

In [11]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [12]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

#### 2.1.7. Summary


#### 2.1.8. Exercises

In [13]:
X == Y, X < Y, X > Y

(tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [14]:
a = torch.arange(9, dtype = torch.int32).reshape((3, 1, 3))
b = torch.arange(27, dtype = torch.int32).reshape((3, 3, 3))
a + b

tensor([[[ 0,  2,  4],
         [ 3,  5,  7],
         [ 6,  8, 10]],

        [[12, 14, 16],
         [15, 17, 19],
         [18, 20, 22]],

        [[24, 26, 28],
         [27, 29, 31],
         [30, 32, 34]]], dtype=torch.int32)

References: [Broadcasting_Rules](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)