#### 2.3.1. Scalars

In [2]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

#### 2.3.2. Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2]

tensor(2)

In [7]:
len(x)

3

In [8]:
x.shape

torch.Size([3])

#### 2.3.3. Matrices

In [9]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### 2.3.4. Tensors

In [12]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

#### 2.3.5. Basic Properties of Tensor Arithmetic

In [13]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [14]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [15]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

#### 2.3.6. Reduction

In [16]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [17]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [19]:
A.shape, A.sum(axis=0).shape, A.sum()

(torch.Size([2, 3]), torch.Size([3]), tensor(15.))

In [20]:
A.shape, A.sum(axis=1).shape, A.sum()

(torch.Size([2, 3]), torch.Size([2]), tensor(15.))

In [21]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [22]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [23]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

#### 2.3.7. Non-Reduction Sum

In [24]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [25]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [26]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

#### 2.3.8. Dot Products

In [27]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [28]:
torch.sum(x * y)

tensor(3.)

#### 2.3.9. Matrix–Vector Products

In [29]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

#### 2.3.10. Matrix–Matrix Multiplication

In [30]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

#### 2.3.11. Norms

In [31]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [32]:
torch.abs(u).sum()

tensor(7.)

In [33]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

#### 2.3.12. Discussion

#### 2.3.13. Exercises

##### Ex4

In [35]:
X = torch.randn(2, 3, 4)

len(X)


2

##### Ex5
Axis = 0

##### Ex6

In [39]:
A/A.sum(axis=1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [40]:
A/A.sum(axis=1, keepdim = True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

##### Ex8

- axis1: Tensor có kích thước (2, 3, 4) sẽ giảm xuống kích thước (3, 4) 
- aixs2: Tensor sẽ giảm xuống kích thước (2, 4) 
- axis3: Tensor sẽ giảm xuống kích thước (2, 3) 

##### Ex9


In [45]:
X = torch.randn(2, 3, 4, 5)

norm = torch.linalg.norm(X)
X.shape, norm


(torch.Size([2, 3, 4, 5]), tensor(11.6734))

##### Ex12

In [47]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)


tensor = torch.stack([A, B, C])

B_recovered = tensor[1]

B_recovered == B

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])